"""LangGraph node functions — process, tools, human_gate, and routing logic."""

import os
import structlog

from langchain_core.messages import AIMessage, SystemMessage, ToolMessage

from core.schemas import SessionStatus
from agents.state import AgentState
from agents.mcp_tools import get_mcp_tools_cache
from agents.user_mcp_tools import get_user_mcp_tools
from llm.router import get_llm, TaskType

logger = structlog.get_logger(__name__)

MAX_ATTEMPTS = int(os.getenv("AGENT_MAX_ATTEMPTS", "3"))


async def get_all_tools(state: AgentState) -> list:
    """Retrieve all bound tools (RAG & user-specific MCP) dynamically."""
    all_tools = []
    
    # Add local docs RAG search tool
    from agents.tools.local_docs import search_local_docs
    all_tools.append(search_local_docs)

    cached_tools = get_mcp_tools_cache()
    if cached_tools is not None:
        all_tools.extend(cached_tools)

    user_id = state.get("user_id")
    if user_id:
        user_tools = await get_user_mcp_tools(user_id)
        all_tools.extend(user_tools)
        
    return all_tools


async def node_process(state: AgentState) -> dict:
    """Main reasoning node — calls LLM with bound MCP tools and returns AI response."""
    try:
        llm = get_llm(TaskType.REASONING)

        all_tools = await get_all_tools(state)

        if all_tools:
            llm = llm.bind_tools(all_tools)

        # Build a single unified SystemMessage containing both the thinking instructions and memory context
        system_contents = [
            "Prior to writing your final response, you MUST output your step-by-step thinking process, search strategy, and planning inside <thought>...</thought> tags at the very beginning of your output. Once done, close the tag and write your final user-facing response."
        ]

        other_messages = []
        if state["messages"]:
            for msg in state["messages"]:
                if isinstance(msg, SystemMessage):
                    if msg.content and msg.content not in system_contents:
                        system_contents.append(msg.content)
                else:
                    other_messages.append(msg)

        unified_system_msg = SystemMessage(content="\n\n".join(system_contents))
        messages_to_send = [unified_system_msg] + other_messages

        full_chunk = None
        async for chunk in llm.astream(messages_to_send):
            if full_chunk is None:
                full_chunk = chunk
            else:
                full_chunk += chunk

        # Extract text content and tool calls from accumulated chunks
        content = ""
        tool_calls = []
        if full_chunk:
            if full_chunk.content:
                if isinstance(full_chunk.content, list):
                    for block in full_chunk.content:
                        if isinstance(block, dict) and block.get("type") == "text":
                            content += block.get("text", "")
                        elif isinstance(block, str):
                            content += block
                elif isinstance(full_chunk.content, str):
                    content = full_chunk.content
                else:
                    content = str(full_chunk.content)
            if hasattr(full_chunk, "tool_calls") and full_chunk.tool_calls:
                tool_calls = full_chunk.tool_calls

        ai_message = AIMessage(content=content, tool_calls=tool_calls)

        return {
            "messages": [ai_message],
            "result": content,
            "errors": [],
            "status": SessionStatus.COMPLETE,
            "last_node": "process",
        }
    except Exception as e:
        logger.error("supervisor_node_process_failed", error=str(e))
        import traceback
        traceback.print_exc()

        prior = state.get("errors", [])
        errors = [str(e)] + prior
        errors = errors[:3]
        return {
            "errors": errors,
            "attempts": min(state.get("attempts", 0) + 1, MAX_ATTEMPTS),
            "status": SessionStatus.FAILED,
            "last_node": "process",
        }


async def node_tools(state: AgentState) -> dict:
    """Dynamic tool execution node — runs all tool calls generated by the LLM."""
    last_msg = state["messages"][-1]
    all_tools = await get_all_tools(state)
    tools_by_name = {t.name: t for t in all_tools}
    
    tool_outputs = []
    for tc in last_msg.tool_calls:
        name = tc["name"]
        args = tc["args"]
        call_id = tc["id"]
        
        if name in tools_by_name:
            tool = tools_by_name[name]
            try:
                output = await tool.ainvoke(args)
            except Exception as e:
                output = f"Error executing tool {name}: {e}"
        else:
            output = f"Error: Tool '{name}' not found"
            
        tool_outputs.append(
            ToolMessage(content=str(output), name=name, tool_call_id=call_id)
        )
        
    return {"messages": tool_outputs, "last_node": "tools"}


def node_human_gate(state: AgentState) -> dict:
    """Human approval node — marks conversation as approved on resume."""
    return {"approved": True, "status": SessionStatus.AWAITING_APPROVAL, "last_node": "human_gate"}


def route_after_process(state: AgentState) -> str:
    """Route based on state after process node runs."""
    if state.get("errors"):
        if state.get("attempts", 0) >= MAX_ATTEMPTS:
            return "end"
        return "process"
        
    messages = state.get("messages", [])
    if messages and hasattr(messages[-1], "tool_calls") and messages[-1].tool_calls:
        return "tools"
        
    if not state.get("approved", False):
        return "human_gate"
    return "end"